version: "3"

# 두 docker-compose.yml 모두 포트만 다를 뿐 띄우는 컨테이너 정보는 동일
services:
  api_server:
    container_name: greenroom-server-blue
    build:
      context: ./module-api
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - /tmp/log:/app/log